version: '3'
services:
  postgres:
    container_name: glow-test-db
    image: postgres:15.1
    restart: always
    environment:
      POSTGRES_USER: glow_user
      POSTGRES_PASSWORD: vOgldnc3NtKZJWSADJBjg
      POSTGRES_DB: glow_development
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - '5432:5432'

volumes:
  postgres:
